version: '3'
services:
  web:
    image: 617608773253.dkr.ecr.us-east-2.amazonaws.com/mathnet/server:latest
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./tmp/db:/data/db

