version: '3'
services:
  web:
    build: .
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ../database/db:/data/db

